export const mockEvents = [
    {
        date: "23",
        month: "SEP",
        title: "Jetpack Comedy",
        time: "12:30PM PST",
        attendees: [
            { src: "https://randomuser.me/api/portraits/men/1.jpg", alt: "User 1" },
            { src: "https://randomuser.me/api/portraits/men/2.jpg", alt: "User 2" },
            { src: "https://randomuser.me/api/portraits/men/3.jpg", alt: "User 3" },
            { src: "https://randomuser.me/api/portraits/men/4.jpg", alt: "User 4" },
            { src: "https://randomuser.me/api/portraits/men/5.jpg", alt: "User 5" },
        ],
        ticketsSold: 875,
        ticketsTotal: 1023,
        inCart: 2,
        revenue: 1482,
        progressColor: "bg-green-500",
    },
    {
        date: "23",
        month: "SEP",
        title: "Adrenaline",
        time: "12:30PM PST",
        attendees: [
            { src: "https://randomuser.me/api/portraits/men/6.jpg", alt: "User 1" },
            { src: "https://randomuser.me/api/portraits/men/7.jpg", alt: "User 2" },
            { src: "https://randomuser.me/api/portraits/men/8.jpg", alt: "User 3" },
            { src: "https://randomuser.me/api/portraits/men/9.jpg", alt: "User 4" },
            { src: "https://randomuser.me/api/portraits/men/10.jpg", alt: "User 5" },
        ],
        ticketsSold: 240,
        ticketsTotal: 500,
        inCart: 2,
        revenue: 1482,
        progressColor: "bg-orange-500",
    },
    {
        date: "23",
        month: "SEP",
        title: "The Reading Out of Your Notebook",
        time: "12:30PM PST",
        attendees: [
            { src: "https://randomuser.me/api/portraits/men/3.jpg", alt: "User 1" },
            { src: "https://randomuser.me/api/portraits/men/4.jpg", alt: "User 2" },
            { src: "https://randomuser.me/api/portraits/men/6.jpg", alt: "User 3" },
            { src: "https://randomuser.me/api/portraits/men/1.jpg", alt: "User 4" },
            { src: "https://randomuser.me/api/portraits/men/5.jpg", alt: "User 5" },
        ],
        ticketsSold: 15,
        ticketsTotal: 889,
        inCart: 2,
        revenue: 1482,
        progressColor: "bg-red-500",
    },
    {
        date: "23",
        month: "SEP",
        title: "Mister Vape Face Dies on Stage",
        time: "12:30PM PST",
        attendees: [
            { src: "https://randomuser.me/api/portraits/men/8.jpg", alt: "User 1" },
            { src: "https://randomuser.me/api/portraits/men/6.jpg", alt: "User 2" },
            { src: "https://randomuser.me/api/portraits/men/5.jpg", alt: "User 3" },
            { src: "https://randomuser.me/api/portraits/men/3.jpg", alt: "User 4" },
            { src: "https://randomuser.me/api/portraits/men/1.jpg", alt: "User 5" },
        ],
        ticketsSold: 875,
        ticketsTotal: 1023,
        inCart: 2,
        revenue: 1482,
        progressColor: "bg-green-500",
    },
    {
        date: "23",
        month: "SEP",
        title: "The Nicole Show",
        time: "12:30PM PST",
        attendees: [
            { src: "https://randomuser.me/api/portraits/men/9.jpg", alt: "User 1" },
            { src: "https://randomuser.me/api/portraits/men/12.jpg", alt: "User 2" },
            { src: "https://randomuser.me/api/portraits/men/6.jpg", alt: "User 3" },
            { src: "https://randomuser.me/api/portraits/men/12.jpg", alt: "User 4" },
            { src: "https://randomuser.me/api/portraits/men/3.jpg", alt: "User 5" },
        ],
        ticketsSold: 240,
        ticketsTotal: 500,
        inCart: 2,
        revenue: 1482,
        progressColor: "bg-orange-500",
    },
];
